## code to prepare `invalid_city` dataset goes here
invalid_city <- c(
  "",
  "ANYWHERE",
  "EVERYWHERE",
  "INFO PENDING",
  "INFO REQUESTED",
  "INFORMATION REQUESTED",
  "INTERNET",
  "IR",
  "N A",
  "N/A",
  "NA",
  "NO INFORMATION GIVEN",
  "NO ADDRESS",
  "NON REPORTABLE",
  "NONE",
  "NONE GIVE",
  "NONE GIVEN",
  "NOT APPLICABLE",
  "NOT AVAILABLE",
  "NOT GIVEN",
  "NOT KNOWN",
  "NOT PROVIDED",
  "NOT REQUIRED",
  "NOT STATED",
  "NOT SURE",
  "NOTAPPLICABLE",
  "NULL",
  "ON LINE",
  "ONLINE",
  "ONLINE COMPANY",
  "ONLINE SERVICE",
  "PENDING",
  "PO BOX",
  "P O BOX",
  "REQUESTED",
  "REQUESTED INFO",
  "REQUESTED INFORMATION",
  "SOMEWHERE",
  "TEST",
  "TO FIND OUT",
  "UNK",
  "UNKNOWN CITY",
  "UNKOWN",
  "VARIOUS",
  "WEB",
  "WEBSITE",
  "WWW",
  "VIRTUAL",
  "XXX",
  "XXXX",
  "XXXXX",
  "XXXXXX",
  "UK",
  "UNKNOWN",
  "NO CITY",
  "MISSING"
)

usethis::use_data(invalid_city, overwrite = TRUE)
